<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'registro_empresa'=>'Company registration',
  'informacion_alterna'=>'Alternate information',
  'nombre_empresa'=>'Type company name',
  'numero_empresa'=>'Type company number',
  'direccion_empresa'=>'Type company address',
  'telefono_empresa'=>'Type company telephone',
  'tipo_empresa'=>'Type company type',
  'actividad_empresa'=>'Type company activity or company description',
  'web_empresa'=>'Type company web',
  'continente_empresa'=>'Type company continent',
  'continente_empresa'=>'Type continent',
  'pais_empresa'=>'Type country',
  'estado_empresa'=>'Type state',
  'ciudad_empresa'=>'Type city',
  'observacion_empresa'=>'Type company observations',
  'email_empresa'=>'Type company email',
  'agrega_email'=>'Add email',
  'redsocial_empresa'=>'Type social network',
  'agrega_redsocial'=>'Add social network',
  'registrar'=>'Save',
  'editar'=>'Edit',
  'cancelar_edicion'=>'Cancel edition',
  'continente'=>'Continent',
  'pais'=>'Country',
  'estado'=>'State',
  'ciudad'=>'City',
  'criterio_busqueda'=>'Search criterials',
  'mostrar_ocultar'=>'Show/hide',
);
